#!/usr/bin/env python3
"""
Update training-data.js from the latest Strava export.

Strava lets you download a full data export (a dated folder). Drop each new
export into:

    ~/StravaExports/<MM DD YY>/

(Kept outside ~/Documents so the weekly background job can read it —
macOS blocks background agents from Documents/Desktop/Downloads.)

This script finds the newest dated folder, reads its activities.csv, and
regenerates training-data.js (all Run + Ride sessions). Each export is a full
snapshot, so this is a clean re-import every time — no merging.

Usage:
    python3 update-sport-data.py            # regenerate training-data.js
    python3 update-sport-data.py --commit   # ...and git commit + push if it changed

Exit codes: 0 = up to date / updated, 2 = no export found.
"""

import csv
import os
import re
import subprocess
import sys
from datetime import datetime

# ── Paths ─────────────────────────────────────────────────────────────
STRAVA_DIR = os.path.expanduser("~/StravaExports")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_FILE = os.path.join(HERE, "training-data.js")

# Folder names look like "08 26 26" (MM DD YY). Also accept a few separators.
DATE_DIR_RE = re.compile(r"^(\d{2})[ _.-](\d{2})[ _.-](\d{2})$")


def find_latest_export(base):
    """Return (path, label_date) for the newest dated export folder."""
    if not os.path.isdir(base):
        return None, None
    candidates = []
    for name in os.listdir(base):
        full = os.path.join(base, name)
        if not os.path.isdir(full):
            continue
        if not os.path.isfile(os.path.join(full, "activities.csv")):
            continue
        m = DATE_DIR_RE.match(name.strip())
        if m:
            mm, dd, yy = (int(x) for x in m.groups())
            try:
                key = datetime(2000 + yy, mm, dd)
            except ValueError:
                key = datetime.fromtimestamp(os.path.getmtime(full))
        else:
            # Un-dated folder (e.g. export_123456): fall back to mtime
            key = datetime.fromtimestamp(os.path.getmtime(full))
        candidates.append((key, full))
    if not candidates:
        return None, None
    candidates.sort()
    key, path = candidates[-1]
    return path, key


def num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return 0.0


def fmt_time(sec):
    sec = int(round(sec))
    h, m, s = sec // 3600, (sec % 3600) // 60, sec % 60
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


def build_sessions(csv_path):
    out = []
    with open(csv_path, newline="") as f:
        for row in csv.DictReader(f):
            t = row["Activity Type"]
            if t == "Ride":
                sport = "Bike"
            elif t == "Run":
                sport = "Run"
            else:
                continue  # hikes / walks left out on purpose
            d = datetime.strptime(row["Activity Date"], "%b %d, %Y, %I:%M:%S %p")
            km = num(row["Distance"]) / 1000.0
            sec = num(row["Moving Time"])
            elev = num(row["Elevation Gain"])
            if km < 0.3 or sec < 60:
                continue  # drop GPS glitches / accidental starts
            out.append((d, sport, round(km, 2), fmt_time(sec), round(elev)))
    out.sort(key=lambda r: r[0])
    return out


HEADER = """/* ============================================================
   TRAINING LOG  —  Elisabetta Rappo
   ------------------------------------------------------------
   AUTO-GENERATED by update-sport-data.py from my latest Strava
   export — do not edit by hand; re-run the script instead.

   Fields:
     date        "YYYY-MM-DD"
     sport       "Run" or "Bike"
     distance_km number   (kilometres)
     time        "MM:SS" or "H:MM:SS"  (moving time)
     elev_m      number   (elevation gain, metres)

   Pace (Run, min/km) and speed (Bike, km/h) are computed by the page.
   ============================================================ */

window.TRAINING_DATA = ["""


def render(sessions):
    lines = [HEADER]
    for d, sp, km, tm, elev in sessions:
        lines.append(
            f'  {{ date: "{d.strftime("%Y-%m-%d")}", sport: "{sp}", '
            f'distance_km: {km}, time: "{tm}", elev_m: {elev} }},'
        )
    lines.append("];")
    return "\n".join(lines) + "\n"


def git(*args):
    return subprocess.run(
        ["git", *args], cwd=HERE, capture_output=True, text=True
    )


def main():
    export, when = find_latest_export(STRAVA_DIR)
    if not export:
        print(f"No Strava export found under: {STRAVA_DIR}", file=sys.stderr)
        return 2

    sessions = build_sessions(os.path.join(export, "activities.csv"))
    new_content = render(sessions)

    old_content = ""
    if os.path.exists(OUT_FILE):
        with open(OUT_FILE) as f:
            old_content = f.read()

    label = when.strftime("%Y-%m-%d") if when else "unknown date"
    if new_content == old_content:
        print(f"Already up to date ({len(sessions)} sessions, latest export {label}).")
        return 0

    with open(OUT_FILE, "w") as f:
        f.write(new_content)
    latest = sessions[-1][0].strftime("%Y-%m-%d") if sessions else "—"
    print(
        f"Updated training-data.js — {len(sessions)} sessions "
        f"from export '{os.path.basename(export)}' (last activity {latest})."
    )

    if "--commit" in sys.argv:
        git("add", "training-data.js")
        st = git("status", "--porcelain", "training-data.js").stdout.strip()
        if not st:
            print("Nothing staged; skipping commit.")
            return 0
        msg = f"Sport: refresh training data from Strava export {label}"
        c = git("commit", "-m", msg)
        if c.returncode != 0:
            print(c.stdout + c.stderr, file=sys.stderr)
            return 1
        p = git("push", "origin", "main")
        print((c.stdout + p.stdout + p.stderr).strip())

    return 0


if __name__ == "__main__":
    sys.exit(main())
